# Generated by Django 4.2.11 on 2024-03-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatedetails',
            name='certType',
            field=models.CharField(choices=[('ppc', 'PPC'), ('matex', 'Matex')], default='unknown', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatedetails',
            name='expiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persondetails',
            name='nhsNumber',
            field=models.CharField(default='unknown', max_length=10),
            preserve_default=False,
        ),
    ]
