# Generated by Django 4.2.11 on 2024-03-06 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ppc_app', '0002_certificatedetails_certtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetails',
            name='userID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
